spring.application.name=CandidateAndPosition-Management
spring.datasource.url=jdbc:mysql://localhost:3306/poc
spring.datasource.username= root
spring.datasource.password=Hira12$$
spring.jpa.hibernate.ddl-auto=update
